baseURL = "https://selimkuzucu.github.io"
title = "Selim Kuzucu"
theme = "researcher"
disableKinds = ["taxonomy", "term"]

[params]
  author = "Selim Kuzucu"
  favicon = "favicon.ico"
  lang = "en"
  # [params.footer]
  #   text = "By Selim Kuzucu"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    pageWidth = "850px"
    avatarSize = "120px"
    colorBlack = "#222222"
    colorRed = "#dc3545"
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "Github"
    url = "https://github.com/selimkuzucu"
  [[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/SelimKuzucu"


[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url  = "/"
    weight = 1
  [[menu.main]]
    name = "Contact"
    url  = "/contact"
    weight = 2
  [[menu.main]]
    name = "Resume"
    url = "/selim_kuzucu_cv.pdf"
    weight = 4
